name: complete
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-279.2.beta <4.0.0'

dependencies:
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  firebase_ui_auth: ^1.14.0
  firebase_ui_oauth_google: ^1.2.17
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^6.2.1
  intl: ^0.18.1
  cloud_firestore: ^4.15.9
  flutter_masked_text2: ^0.9.1
  intl_phone_number_input: ^0.7.4
  flutter_secure_storage: ^9.0.0
  percent_indicator: ^4.2.3
  fl_chart: ^0.67.0
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  hive: ^2.2.3
  dev: ^1.0.0
  hive_flutter: ^1.1.0
  firebase_dynamic_links: ^5.5.0
  flutter_switch: ^0.3.2
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  http: ^1.0.0
  stripe: ^4.11.0
  dotenv: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.1.4
  hive_generator: ^2.0.1
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  http: ^1.0.0 

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/icon.jpg
    - assets/data/alimentos.json
   
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.jpg"
