// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN8U-IDzMMPo6Rj8bwCvexN0fsW5rDCv8',
    appId: '1:120455771575:web:060d7f9366f2f7ef7a6432',
    messagingSenderId: '120455771575',
    projectId: 'revo-nutri',
    authDomain: 'revo-nutri.firebaseapp.com',
    databaseURL: 'https://revo-nutri-default-rtdb.firebaseio.com',
    storageBucket: 'revo-nutri.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYiLAes-npZ63KWljNNYjVBnZNufmF6Bw',
    appId: '1:120455771575:android:60ea9b1fe32128d87a6432',
    messagingSenderId: '120455771575',
    projectId: 'revo-nutri',
    databaseURL: 'https://revo-nutri-default-rtdb.firebaseio.com',
    storageBucket: 'revo-nutri.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBaQQjCaHiP1dG9X8rLySIwVL_4XCjRC4',
    appId: '1:120455771575:ios:7b874fe733c000787a6432',
    messagingSenderId: '120455771575',
    projectId: 'revo-nutri',
    databaseURL: 'https://revo-nutri-default-rtdb.firebaseio.com',
    storageBucket: 'revo-nutri.appspot.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBaQQjCaHiP1dG9X8rLySIwVL_4XCjRC4',
    appId: '1:120455771575:ios:a727b15bb9c741817a6432',
    messagingSenderId: '120455771575',
    projectId: 'revo-nutri',
    databaseURL: 'https://revo-nutri-default-rtdb.firebaseio.com',
    storageBucket: 'revo-nutri.appspot.com',
    iosBundleId: 'com.example.complete.RunnerTests',
  );
}
